apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ROLE_ARN
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::AWS_ACCOUNT_ID:role/bootifulmicropizza-eks-cluster-admin-role
      username: eks_admin_role
      groups:
        - system:masters
